# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'


target 'Runner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyBootpay', '~> 2.1.18'

  # Pods for Runner

end
